### ISSUE TITLE
Can you put these two nodes in the same category? I found that the nodes in these two categories are all from your plugin after uninstalling all plugins

### ISSUE THREAD

**Issue by wibur0620** [ratulrafsan/Comfyui-SAL-VTON#1]
![image](https://github.com/ratulrafsan/Comfyui-SAL-VTON/assets/131615326/d2243732-7fe5-4c06-9308-10bf85572c2d)
![image](https://github.com/ratulrafsan/Comfyui-SAL-VTON/assets/131615326/b236f08c-900b-400a-8cd9-ed70e2400d5e)
![image](https://github.com/ratulrafsan/Comfyui-SAL-VTON/assets/131615326/caa18329-fec4-4f02-81b3-898401a9d665)
![image](https://github.com/ratulrafsan/Comfyui-SAL-VTON/assets/131615326/8b8e14e1-957c-4fc1-838e-e8f9aa30280a)

**Comment by ratulrafsan** [comment]
Thanks for pointing that out.
I didn't initially intend to publish the random image selector node. So, I forgot to update the category.

Fixed now.
