### ISSUE TITLE
Questions about dimensions?

### ISSUE THREAD

**Issue by ClothingAI** [ratulrafsan/Comfyui-SAL-VTON#12]
Why the garmet HAS TO BE  768x1024?
Is it because the text to image output is an image of 1024 x 1024? 

I would like to have an explanation, the "why"?

**Comment by ratulrafsan** [comment]
[Keyu Y. Tingwei G. et al. (2023). Linking Garment with Person via Semantically Associated Landmakrs for Virtual Try-On](https://openaccess.thecvf.com/content/CVPR2023/papers/Yan_Linking_Garment_With_Person_via_Semantically_Associated_Landmarks_for_Virtual_CVPR_2023_paper.pdf)
See section 4 - Experiments. VITON-HD is trained on 768x1024.
