### ISSUE TITLE
I don't understand this error, but I can find the node.

### ISSUE THREAD

**Issue by Tanglinling** [ratulrafsan/Comfyui-SAL-VTON#2]
![image](https://github.com/ratulrafsan/Comfyui-SAL-VTON/assets/146339730/7f5cf966-650a-4b33-8ecf-b1af3eacf919)

**Comment by Florin-Birgu** [comment]
Can you try running:
`pip install pillow`

**Comment by ratulrafsan** [comment]
Installing through comfy-cli should solve the issue. Conflicting packages were removed in later version.
