### ISSUE TITLE
Install errors

### ISSUE THREAD

**Issue by SimithWang** [ratulrafsan/Comfyui-SAL-VTON#6]
![image](https://github.com/ratulrafsan/Comfyui-SAL-VTON/assets/40049710/4fb9945f-cace-42a0-8144-b478b7a66e11)
![image](https://github.com/ratulrafsan/Comfyui-SAL-VTON/assets/40049710/5cee7907-9be6-4ce7-8f69-6bf9c86825ad)

can not install all the dependences, encounter errors

**Comment by ratulrafsan** [comment]
Please install through ComfyUI registry. Thanks.
