### ISSUE TITLE
The only thing that bugs me (sorry, I'm a visual person) is the logo on the app. Feels a little bloggy. Is there a way to replace the font or the png so it is a little more standard?

### ISSUE THREAD

**Issue by rafstahelin** [ratulrafsan/Comfyui-SAL-VTON#7]

**Comment by ratulrafsan** [comment]
What logo are you talking about? Can you share screenshots of it? There's no reference to any logo or font in the entire code base.

**Comment by rafstahelin** [comment]
Sorry, somehow I managed to write on the wrong repo Best, Raf On 14 Jul 2024, at 14:09, Rafsan Ratul ***@***.***> wrote:﻿
What logo are you talking about? Can you share screenshots of it? There's no reference to any logo or font in the entire code base.
